bind 127.0.0.1
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300
databases 16
save ""
appendonly no
stop-writes-on-bgsave-error no
dbfilename dump.rdb
dir c:/Users/NyGsoft/Desktop/server_dicloak
loglevel notice
logfile "c:/Users/NyGsoft/Desktop/server_dicloak/redis-dev.log"
